In [233]:
import pandas as pd
import numpy as np

In [234]:
X = np.array([1.4, 1.0, 1.5, 3.1, 3.8, 4.1])
print(X)

[1.4 1.  1.5 3.1 3.8 4.1]


In [235]:
C = X[:2]
print(C)

[1.4 1. ]


In [236]:
np.abs(X - C[0])

array([0. , 0.4, 0.1, 1.7, 2.4, 2.7])

In [237]:
np.abs(X - C[1])

array([0.4, 0. , 0.5, 2.1, 2.8, 3.1])

In [238]:
data = X[:, np.newaxis]
data

array([[1.4],
       [1. ],
       [1.5],
       [3.1],
       [3.8],
       [4.1]])

In [239]:
np.abs(data - C)

array([[0. , 0.4],
       [0.4, 0. ],
       [0.1, 0.5],
       [1.7, 2.1],
       [2.4, 2.8],
       [2.7, 3.1]])

In [240]:
D = np.abs(data - C)
D

array([[0. , 0.4],
       [0.4, 0. ],
       [0.1, 0.5],
       [1.7, 2.1],
       [2.4, 2.8],
       [2.7, 3.1]])

In [241]:
L = np.argmin(D, axis = 1)
L

array([0, 1, 0, 0, 0, 0])

In [242]:
X[L == 0].mean()

np.float64(2.7800000000000002)

In [243]:
X[L == 1].mean()

np.float64(1.0)

In [244]:
np.array([X[L == i].mean() for i in range(2)])

array([2.78, 1.  ])

In [245]:
print(np.all([True, False]))
print(np.all([False, True]))
print(np.all([False, False]))
print(np.all([True, True]))

False
False
False
True


In [246]:
k = 2
centroids = X[:k]
print(X)
print(centroids)

[1.4 1.  1.5 3.1 3.8 4.1]
[1.4 1. ]


In [247]:
inter = 10
for i in range(inter):
    # 2. Compute distances
    distances = np.abs(X.reshape(-1, 1) - centroids)
    print("distances:\n ", distances)
    
    # 3. Compute labels
    labels = np.argmin(distances, axis = 1)
    print("labels:\n ",labels)
    # 4. Update centroids
    centroids_new = np.array([X[labels == j].mean() for j in range(k)])
    #check
    if np.all(centroids == centroids_new):
        break
    centroids = centroids_new
    print("centroids:\n ", centroids)
wcss = np.sum([np.sum(np.square(X[labels == i] - centroids[i])) for i in range(2)])
print(wcss)

distances:
  [[0.  0.4]
 [0.4 0. ]
 [0.1 0.5]
 [1.7 2.1]
 [2.4 2.8]
 [2.7 3.1]]
labels:
  [0 1 0 0 0 0]
centroids:
  [2.78 1.  ]
distances:
  [[1.38 0.4 ]
 [1.78 0.  ]
 [1.28 0.5 ]
 [0.32 2.1 ]
 [1.02 2.8 ]
 [1.32 3.1 ]]
labels:
  [1 1 1 0 0 0]
centroids:
  [3.66666667 1.3       ]
distances:
  [[2.26666667 0.1       ]
 [2.66666667 0.3       ]
 [2.16666667 0.2       ]
 [0.56666667 1.8       ]
 [0.13333333 2.5       ]
 [0.43333333 2.8       ]]
labels:
  [1 1 1 0 0 0]
0.6666666666666662


In [248]:
X

array([1.4, 1. , 1.5, 3.1, 3.8, 4.1])

In [249]:
# Using library
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=2, max_iter=10)
kmeans.fit(X.reshape(-1, 1))

labels = kmeans.labels_

centroids = kmeans.cluster_centers_

new_data = np.array([1.5, 8.2]).reshape(-1, 1)
predictions = kmeans.predict(new_data)

print(labels)
print(centroids)
print(predictions)

[0 0 0 1 1 1]
[[1.3       ]
 [3.66666667]]
[0 1]


In [250]:
data = np.random.rand(32, 4)
print(data.shape)


centroids = np.random.rand(3, 4)
print(centroids.shape)

print(data[:, np.newaxis, :].shape)
distances = np.sqrt((data[:, np.newaxis, :] - centroids) ** 2)
print(distances.shape)

(32, 4)
(3, 4)
(32, 1, 4)
(32, 3, 4)


In [251]:
X = np.array([
    [18, 80],
    [20, 90],
    [22, 85],
    [30, 50],
    [34, 64],
    [40, 60],
    [60, 30],
    [66, 40],
    [70, 25]
])
C = np.array([
    [22, 85],
    [30, 50],
    [34, 64]
])

In [252]:
np.linalg.norm(X[:, np.newaxis, :] - C, axis = 2)

array([[ 6.40312424, 32.31098884, 22.627417  ],
       [ 5.38516481, 41.23105626, 29.52964612],
       [ 0.        , 35.90264614, 24.18677324],
       [35.90264614,  0.        , 14.56021978],
       [24.18677324, 14.56021978,  0.        ],
       [30.8058436 , 14.14213562,  7.21110255],
       [66.85057965, 36.05551275, 42.80186912],
       [62.93647591, 37.36308338, 40.        ],
       [76.83749085, 47.16990566, 53.07541804]])

In [253]:
age = np.array([18, 20, 22,
                30, 34, 40,
                60, 66, 70])
expenditure = np.array([80, 90, 85, 50, 64, 60, 30, 40, 25])

In [254]:
X = np.column_stack((age, expenditure))
print(X)

[[18 80]
 [20 90]
 [22 85]
 [30 50]
 [34 64]
 [40 60]
 [60 30]
 [66 40]
 [70 25]]


In [260]:
k = 3
max_inters = 2
centroids = X[2:k + 2]

for _ in range(max_inters):
    distances = np.linalg.norm(X[:, np.newaxis, :] - centroids, axis = 2)
    labels = np.argmin(distances, axis = 1)

    new_centroids = np.array([X[labels == i].mean(axis = 0) for i in range(k)])
    if np.all(centroids == new_centroids):
        break
    centroids = new_centroids